##############################
# Linhas de comando Comentadas caso
# descomentadas ajudam a percorrer o codigo
##############################

#CREATE SCHEMA LOJA;
#Questao 1
CREATE TABLE PRODUTOS(
ID INT(10) PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100),
DESCRICAO VARCHAR(200),
DESCONTO DECIMAL(10,2),
DATA_VAL DATE);

#INSERT INTO PRODUTOS(NOME,DESCRICAO,DESCONTO,DATA_VAL)
#VALUES ('COXINHA', 'COMIDA',200.00, '2020-01-01');
#INSERT INTO PRODUTOS(NOME,DESCRICAO,DESCONTO,DATA_VAL)
#VALUES ('EMPADA', 'COMIDA',300.00, '2021-01-01');
#INSERT INTO PRODUTOS(NOME,DESCRICAO,DESCONTO,DATA_VAL)
#VALUES ('QUIBE', 'COMIDA',400.00, '2022-01-01');
#INSERT INTO PRODUTOS(NOME,DESCRICAO,DESCONTO,DATA_VAL)
#VALUES ('SALSICHA', 'COMIDA',0.50, '2021-08-15');
#INSERT INTO PRODUTOS(NOME,DESCRICAO,DESCONTO,DATA_VAL)
#VALUES ('PASTEL', 'COMIDA',0.25, '2021-08-16');

#Questao 2
SELECT * FROM PRODUTOS WHERE 
DATA_VAL >= '2020-01-01' AND DATA_VAL <= '2021-08-15';

#Questao 3
SELECT * FROM PRODUTOS WHERE 
DATA_VAL < '2020-01-01' OR DATA_VAL > '2021-08-15';

#Questao 4
CREATE TABLE NOTAS_FISCAIS(
NUMERO INT(10) PRIMARY KEY AUTO_INCREMENT,
IDPRODUTO INT(10),
VALOR DECIMAL(10,2),
FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTOS(ID) 
);

#INSERT INTO PRODUTOS(ID,NOME,DESCRICAO,DESCONTO,DATA_VAL)
#VALUES ('455644','BOLINHO DE QUEIJO', 'COMIDA',10.00, '2024-01-01');
#INSERT INTO NOTAS_FISCAIS (IDPRODUTO,VALOR) 
#VALUES (455644,3000.00);
#INSERT INTO NOTAS_FISCAIS (IDPRODUTO,VALOR) 
#VALUES (1,2000.00);
#INSERT INTO NOTAS_FISCAIS (IDPRODUTO,VALOR) 
#VALUES (2,1500.00);

#Questao 5
SELECT NUMERO FROM NOTAS_FISCAIS WHERE IDPRODUTO = 455644;

#Questao 6
ALTER TABLE NOTAS_FISCAIS CHANGE NUMERO ORDER_ID INT(10);

#Questao 7
INSERT INTO PRODUTOS(ID,NOME,DESCRICAO,DESCONTO,DATA_VAL)
VALUES ('243924','PIZZA', 'COMIDA',8.00, '2018-01-01');
UPDATE NOTAS_FISCAIS SET IDPRODUTO=243924 WHERE IDPRODUTO=455644;
#SELECT * FROM NOTAS_FISCAIS;

#Questao 8
ALTER TABLE PRODUTOS ADD CONSTRAINT VAL_DATA CHECK (DATA_VAL>'2022-01-01') NOT ENFORCED;
ALTER TABLE NOTAS_FISCAIS ADD CONSTRAINT COMPRA_VAL CHECK (VALOR > '1500') NOT ENFORCED;

#SELECT * FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS;