CREATE SCHEMA LOJA_MESTRE_ANDRE;
USE LOJA_MESTRE_ANDRE;
CREATE TABLE PRODUTOS(
ID INT(10) PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100),
DESCRICAO VARCHAR(100),
DESCONTO DECIMAL(10,2),
PRECO DECIMAL(10,2),
DATA_INICIO DATE);
